//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres_korespondencyjny
    {
        public int Adres_korespondencyjnyID { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu_mieszkania { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Kraj { get; set; }

        public virtual ICollection<Kontakt> Kontakt { get; set; }
    }
}
