//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public int DokumentId { get; set; }
        public string Rodzaj_dokumentu { get; set; }
        public string Seria_numer_dokumentu { get; set; }
    
        public virtual Osoba_personalia Osoba_personalia { get; set; }
        public int Osoba_personaliaForeignKey { get; set; }
    }
}
