//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        public int KlientID { get; set; }
        public int Osoba_personaliaID { get; set; }
        public int Para_mlodaID { get; set; }

        public virtual Para_mloda Para_młoda { get; set; }
        public virtual Osoba_personalia Osoba_personalia { get; set; }
    }
}
