//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Wesele_szczegoly = new HashSet<Wesele_szczegoly>();
        }
    
        public int MenuId { get; set; }
        public string Nazwa { get; set; }
        public string Alkohole { get; set; }
        public string Stol_wiejski { get; set; }
        public double Koszt_za_osobe { get; set; }
    
        public virtual ICollection<Wesele_szczegoly> Wesele_szczegoly { get; set; }
    }
}
