//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba_personalia
    {
        public int Osoba_personaliaID { get; set; }
        public int KontaktID { get; set; }
        public int DokumentID { get; set; }
        public int PracownikID { get; set; }

        public string Imie { get; set; }
        public string Drugie_imie { get; set; }
        public string Nazwisko { get; set; }

        public virtual Klient Klient { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Dokument Dokument { get; set; }
        public virtual ICollection<Kontakt> Kontakt { get; set; }
    }
}
