//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public Pracownik()
        {
            this.Umowa = new HashSet<Umowa>();
        }
    
        public int PracownikId { get; set; }
        public string Stanowisko { get; set; }
        public string Data_zatrudnienia { get; set; }
        public double Pensja { get; set; }
        public double Prowizje { get; set; }
    
        public virtual Osoba_personalia Osoba_personalia { get; set; }
        public int Osoba_personaliaForeignKey { get; set; }
        public virtual ICollection<Umowa> Umowa { get; set; }
    }
}
