//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowa
    {
        public Umowa()
        {
            this.Rozliczenia_szczegoly = new HashSet<Rozliczenia_szczegoly>();
        }
    
        public int UmowaId { get; set; }
        public System.DateTime Data_podpisania { get; set; }
        public int Id_pracownika { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual ICollection<Rozliczenia_szczegoly> Rozliczenia_szczegoly { get; set; }
    }
}
